import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { figtree, yekan } from '@/app/styles/fonts/fonts'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Cartsaz',
  description: 'Generated by next js',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html dir="rtl" className={`${yekan.variable} ${figtree.variable}`}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
