import './globals.css'
import type { Metadata } from 'next'
import { figtree, yekan } from '@/app/styles/fonts/fonts'

export const metadata: Metadata = {
  title: 'Cartsaz',
  description: 'Generated by next js',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={`${yekan.variable} ${figtree.variable}`}
    >
      <body>{children}</body>
    </html>
  )
}
